# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ipRangeInput = QtWidgets.QLineEdit(self.centralwidget)
        self.ipRangeInput.setObjectName("ipRangeInput")
        self.verticalLayout.addWidget(self.ipRangeInput)
        self.scanButton = QtWidgets.QPushButton(self.centralwidget)
        self.scanButton.setObjectName("scanButton")
        self.verticalLayout.addWidget(self.scanButton)
        self.resultsTable = QtWidgets.QTableWidget(self.centralwidget)
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.setColumnCount(3)
        self.resultsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.resultsTable)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Network Scanner"))
        self.ipRangeInput.setPlaceholderText(_translate("MainWindow", "Enter IP range (e.g., 192.168.1.0/24)"))
        self.scanButton.setText(_translate("MainWindow", "Scan"))
        item = self.resultsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.resultsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MAC Address"))
        item = self.resultsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Vendor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
